"""
Education Helper - Tooltips, tutorials, and beginner-friendly explanations
"""

# Trading concept glossary
GLOSSARY = {
    "RSI": {
        "name": "Relative Strength Index (RSI)",
        "simple": "A momentum indicator that measures if a stock is overbought or oversold",
        "explanation": """
        RSI ranges from 0-100:
        • Below 30: Oversold (stock might be undervalued, potential BUY)
        • 30-70: Neutral zone
        • Above 70: Overbought (stock might be overvalued, potential SELL)

        Think of it like a thermometer for stock prices!
        """,
        "example": "If AAPL has RSI of 25, it's been falling a lot and might bounce back soon."
    },

    "Mean Reversion": {
        "name": "Mean Reversion Strategy",
        "simple": "The idea that prices tend to return to their average over time",
        "explanation": """
        Like a rubber band:
        • Prices stretch away from average (up or down)
        • Eventually they snap back toward the middle
        • Our strategy buys when stretched down (oversold)
        • Sells when stretched up (overbought)
        """,
        "example": "If a stock usually trades at $100 but drops to $80 for no fundamental reason, mean reversion suggests it will return to $100."
    },

    "Position Size": {
        "name": "Position Size",
        "simple": "How much of a stock you buy",
        "explanation": """
        Position size is how many shares you purchase.

        Smaller position = Less risk, less reward
        Larger position = More risk, more reward

        Our system uses fixed position sizes (e.g., 2 shares) for simplicity.
        Advanced traders adjust based on confidence and risk tolerance.
        """,
        "example": "Buying 2 shares at $200 = $400 position. If it goes up 10%, you make $40."
    },

    "Buying Power": {
        "name": "Buying Power",
        "simple": "The amount of money available to make new trades",
        "explanation": """
        Buying power = Cash + Margin (borrowed money for trading)

        Paper trading accounts often give you $100,000+ to practice with.

        Risk Management checks buying power before each trade to ensure
        you have enough funds.
        """,
        "example": "If you have $10,000 buying power, you can buy stocks worth up to $10,000."
    },

    "Dry Run": {
        "name": "Dry Run Mode (Paper Trading)",
        "simple": "Practice trading with fake money - no real risk!",
        "explanation": """
        Dry Run = Simulated trading
        • Uses real market prices
        • Generates real signals
        • But no actual money is spent
        • Perfect for learning and testing strategies

        Always test strategies in dry run before using real money!
        """,
        "example": "In dry run, if you 'buy' 10 shares of TSLA, it's simulated - you don't actually own TSLA."
    },

    "Signal": {
        "name": "Trading Signal",
        "simple": "A recommendation to BUY, SELL, or HOLD based on market data",
        "explanation": """
        Trading signals are generated by analyzing:
        • Technical indicators (RSI, moving averages, etc.)
        • Price patterns
        • Volume data

        Our system generates signals automatically and explains WHY.

        Types:
        • BUY: Good time to purchase
        • SELL: Good time to exit position
        • HOLD: Do nothing, wait for better opportunity
        """,
        "example": "BUY signal for MSFT because RSI is 18 (very oversold)."
    },

    "Risk Management": {
        "name": "Risk Management",
        "simple": "Rules to protect you from losing too much money",
        "explanation": """
        Our risk management system checks:
        1. Max Trade Value: Don't spend too much on one trade
        2. Max Position %: Don't put all eggs in one basket
        3. Buying Power: Make sure you have funds
        4. Position Limits: Don't overexpose to one stock

        These rules prevent catastrophic losses!
        """,
        "example": "If max trade value is $1000, the system won't let you buy $2000 worth of stock."
    },

    "Confidence": {
        "name": "Signal Confidence",
        "simple": "How sure the strategy is about a trade (0-100%)",
        "explanation": """
        Confidence score indicates strength of signal:
        • 80-100%: Very strong signal
        • 60-80%: Strong signal
        • 40-60%: Moderate signal
        • Below 40%: Weak signal

        Based on:
        • How far RSI is from threshold
        • Other technical factors
        • Market conditions
        """,
        "example": "77% confidence BUY means indicators strongly suggest buying."
    },

    "Audit Log": {
        "name": "Audit Log (Glass Box)",
        "simple": "A complete record of every decision the system makes",
        "explanation": """
        Glass Box = Complete transparency

        Every action is logged with:
        • What happened (FETCH, ANALYZE, VALIDATE, EXECUTE)
        • When it happened (timestamp)
        • Why it happened (rationale)
        • Input data and output results

        You can trace ANY decision back to its reasoning!
        """,
        "example": "See exactly why the system bought MSFT at 10:34 AM - price, RSI, risk checks, everything."
    },

    "Oversold": {
        "name": "Oversold",
        "simple": "When a stock has fallen too much and might bounce back",
        "explanation": """
        Oversold (RSI < 30) means:
        • Stock has been heavily sold
        • Price may have dropped too far
        • Due for a rebound (mean reversion)

        Like a sale at a store - good time to buy!

        Caution: Stocks can stay oversold if there's a real problem.
        """,
        "example": "AAPL at RSI 25 is oversold - many traders would consider buying."
    },

    "Overbought": {
        "name": "Overbought",
        "simple": "When a stock has risen too much and might fall back",
        "explanation": """
        Overbought (RSI > 70) means:
        • Stock has been heavily bought
        • Price may have risen too far
        • Due for a pullback

        Like an overinflated balloon - might pop!

        Good time to take profits or avoid buying.
        """,
        "example": "TSLA at RSI 85 is overbought - many traders would consider selling."
    }
}


def get_tooltip(concept: str) -> dict:
    """
    Get tooltip information for a trading concept

    Args:
        concept: Trading concept name

    Returns:
        Dictionary with name, simple explanation, detailed explanation, example
    """
    concept_key = concept.upper().replace(" ", "_")

    # Try exact match first
    if concept_key in GLOSSARY:
        return GLOSSARY[concept_key]

    # Try partial match
    for key, value in GLOSSARY.items():
        if concept.upper() in key or key in concept.upper():
            return value

    # Return generic response
    return {
        "name": concept,
        "simple": f"A trading concept: {concept}",
        "explanation": "Ask the AI Advisor for a detailed explanation!",
        "example": "Use the chat to learn more."
    }


def get_onboarding_steps() -> list:
    """Get step-by-step onboarding tutorial"""
    return [
        {
            "step": 1,
            "title": "Welcome to Autonomous Alpha! 🎯",
            "content": """
            This is a Glass Box trading system - every decision is transparent and explainable.

            Let's take a quick tour!
            """,
            "action": "Click Next to continue"
        },
        {
            "step": 2,
            "title": "The Dashboard 📊",
            "content": """
            You're looking at 4 main tabs:
            • Live Charts: Real-time prices and RSI indicators
            • Signals: BUY/SELL recommendations
            • Risk Monitor: Safety checks and limits
            • Audit Log: Complete decision history

            Everything updates in real-time!
            """,
            "action": "Explore the tabs"
        },
        {
            "step": 3,
            "title": "Sidebar Configuration ⚙️",
            "content": """
            Customize everything from the sidebar:
            • Choose which stocks to trade
            • Adjust RSI thresholds (when to buy/sell)
            • Set position sizes
            • Configure risk limits

            Don't worry - it's in DRY RUN mode (no real money)!
            """,
            "action": "Try changing a setting"
        },
        {
            "step": 4,
            "title": "AI Trading Advisor 🤖",
            "content": """
            Have questions? Ask the AI Advisor!

            Try asking:
            • "Why did you buy MSFT?"
            • "Explain RSI to me"
            • "What should I do if the market crashes?"

            Get educational, detailed answers.
            """,
            "action": "Ask a question in the chat"
        },
        {
            "step": 5,
            "title": "Start Trading! 🚀",
            "content": """
            Ready to see it in action?

            1. Click "▶ Start Trading" at the top
            2. Watch signals appear in real-time
            3. See risk management in action
            4. Explore the audit logs

            Remember: This is DRY RUN mode - safe to experiment!
            """,
            "action": "Click Start Trading"
        }
    ]


def get_feature_highlights() -> list:
    """Get list of key features for highlighting"""
    return [
        {
            "icon": "🔍",
            "title": "Glass Box Transparency",
            "description": "Every decision is logged with complete reasoning. No black boxes here!"
        },
        {
            "icon": "🤖",
            "title": "AI-Powered Advisor",
            "description": "Chat with Claude 4.6 to understand trades and learn about markets."
        },
        {
            "icon": "🛡️",
            "title": "Multi-Layer Safety",
            "description": "Risk management prevents bad trades automatically."
        },
        {
            "icon": "📚",
            "title": "Educational Mode",
            "description": "Learn as you trade with tooltips and explanations."
        },
        {
            "icon": "🎯",
            "title": "Real-Time Trading",
            "description": "Live market data and instant signal generation."
        },
        {
            "icon": "🗣️",
            "title": "Natural Language",
            "description": "Create strategies by describing them in plain English!"
        }
    ]
